export const COMMENT_LIST_REQUEST = "COMMENT_LIST_REQUEST";
export const COMMENT_LIST_SUCCESS = "COMMENT_LIST_SUCCESS";
export const COMMENT_LIST_FAIL = "COMMENT_LIST_FAIL";

export const COMMENT_CREATE_REQUEST = "COMMENT_CREATE_REQUEST";
export const COMMENT_CREATE_SUCCESS = "COMMENT_CREATE_SUCCESS";
export const COMMENT_CREATE_FAIL = "COMMENT_CREATE_FAIL";

// export const NOTE_UPDATE_REQUEST = "NOTE_UPDATE_REQUEST";
// export const NOTE_UPDATE_SUCCESS = "NOTE_UPDATE_SUCCESS";
// export const NOTE_UPDATE_FAIL = "NOTE_UPDATE_FAIL";