export const PROJECT_LIST_REQUEST = "PROJECT_LIST_REQUEST";
export const PROJECT_LIST_SUCCESS = "PROJECT_LIST_SUCCESS";
export const PROJECT_LIST_FAIL = "PROJECT_LIST_FAIL";

export const PROJECT_CREATE_REQUEST = "PROJECT_REGISTER_REQUEST";
export const PROJECT_CREATE_SUCCESS = "PROJECT_REGISTER_SUCCESS";
export const PROJECT_CREATE_FAIL = "PROJECT_REGISTER_FAIL";