export const SECTION_LIST_FAIL = "SECTION_LIST_FAIL";
export const SECTION_LIST_REQUEST = "SECTION_LIST_REQUEST";
export const SECTION_LIST_SUCCESS = "SECTION_LIST_SUCCESS";
export const SECTION_ORDER_LIST_REQUEST = "SECTION_ORDER_LIST_REQUEST";
export const SECTION_ORDER_LIST_SUCCESS = "SECTION_ORDER_LIST_SUCCESS";
export const SECTION_ORDER_LIST_FAIL = "SECTION_ORDER_LIST_FAIL";