export const SUBTASK_LIST_REQUEST = "SUBTASK_LIST_REQUEST";
export const SUBTASK_LIST_SUCCESS = "SUBTASK_LIST_SUCCESS";
export const SUBTASK_LIST_FAIL = "SUBTASK_LIST_FAIL";

export const SUBTASK_CREATE_REQUEST = "SUBTASK_CREATE_REQUEST";
export const SUBTASK_CREATE_SUCCESS = "SUBTASK_CREATE_SUCCESS";
export const SUBTASK_CREATE_FAIL = "SUBTASK_CREATE_FAIL";

export const SUBTASK_UPDATE_REQUEST = "SUBTASK_UPDATE_REQUEST";
export const SUBTASK_UPDATE_SUCCESS = "SUBTASK_UPDATE_SUCCESS";
export const SUBTASK_UPDATE_FAIL = "SUBTASK_UPDATE_FAIL";

export const SUBTASK_DELETE_REQUEST = "SUBTASK_DELETE_REQUEST";
export const SUBTASK_DELETE_SUCCESS = "SUBTASK_DELETE_SUCCESS";
export const SUBTASK_DELETE_FAIL = "SUBTASK_DELETE_FAIL";